# Generated by Django 5.1.7 on 2025-03-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0002_remove_file_slides_slide_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='slides/'),
        ),
    ]
