# Generated by Django 5.1.7 on 2025-03-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0003_slide_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='file',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='content',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='slide',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='slide',
            name='body_font_size',
            field=models.CharField(default='1rem', max_length=10),
        ),
        migrations.AddField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slides/'),
        ),
        migrations.AddField(
            model_name='slide',
            name='subtitle',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='subtitle_font_size',
            field=models.CharField(default='1.5rem', max_length=10),
        ),
        migrations.AddField(
            model_name='slide',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='slide',
            name='title_font_size',
            field=models.CharField(default='2rem', max_length=10),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
